/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kerberos;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import message.ASAckResponse;
import message.ASRequest;
import message.ASResponse;
import message.TGSRequest;
import message.TGSResponse;
import utils.FileUtils;
import utils.RandomUtils;
import utils.TimeUtils;

/**
 *
 * @author Vitor Tozzi
 */
public class ImplementClient extends javax.swing.JFrame {

    InterfaceAS interfaceAS;
    InterfaceTGS interfaceTGS;
    InterfaceServer interfaceServer;

    String senha;
    String sessionKey;
    String clientID = "cliente";

    /**
     * Creates new form ImplementClient
     */
    public ImplementClient() {
        initComponents();
        initClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kerberos");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Fazer Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario");

        jLabel3.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tUser, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(tSenha))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String user = tUser.getText();
        senha = tSenha.getText();
        if (senha.equals("") || user.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, informe o usuário e senha.");
        } else {
            int random = RandomUtils.getRandom(10000);
            Date date = TimeUtils.getDate();
            // Requisição com validade de 4 horas
            Date timestamp = TimeUtils.addHours(date, 4);

            ASRequest aSRequest = new ASRequest("cliente", "tgs", timestamp, String.valueOf(random));

            System.out.println("***Passo 1***: Requisição do cliente");
            aSRequest.print();

            /**
             * Envia a mensagem criptografada para o diretório do AS
             */
            String location = "F:\\Kerberos\\AS\\clientRequest.des";
            try {
                FileUtils fileUtils = new FileUtils(senha);
                fileUtils.writeEncryptedObject(aSRequest.clientRequest, location);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeySpecException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            }

            /**
             * Retorno do AS
             */
            try {
                interfaceAS.doLogin(aSRequest);
                checkASResponse();
            } catch (RemoteException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeyException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidKeySpecException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchPaddingException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ImplementClient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void checkASResponse() throws InvalidKeyException, NoSuchAlgorithmException, InvalidKeySpecException, NoSuchPaddingException, IOException, FileNotFoundException, ClassNotFoundException {

        FileUtils fileUtils = new FileUtils(senha);

        String clientACKFilepath = "F:\\Kerberos\\Client\\ack.des";
        ASAckResponse ackResponse = (ASAckResponse) fileUtils.readEncryptedObject(clientACKFilepath);

        System.out.println("***Passo 2***: ACK recebida pelo cliente");
        ackResponse.print();

        /**
         * Envia a requisição para o TGS cifrado com a chave da sessão
         */
        this.sessionKey = ackResponse.sessionKey;

        // Timestamp de 8 horas
        Date timestamp = TimeUtils.addHours(TimeUtils.getDate(), 8);
        String randomNumber = String.valueOf(RandomUtils.getRandom(10000));
        TGSRequest tgsr = new TGSRequest(clientID, "servidor", timestamp, randomNumber);

        String tgsRequestFilepath = "F:\\Kerberos\\TGS\\clientRequest.des";

        fileUtils = new FileUtils(sessionKey);
        fileUtils.writeEncryptedObject(tgsr, tgsRequestFilepath);

        /**
         * Faz com que o TGS valide o ticket, para então o TGS desencriptar o
         * pedido do cliente
         */
        String clientTicketFilepath = "F:\\Kerberos\\Client\\tgs_ticket.des";
        interfaceTGS.readTicketFromClient(clientTicketFilepath);

        /**
         * Realiza leitura de retorno do TGS
         */
        String clientTGSResponseFilepath = "F:\\Kerberos\\Client\\tgsResponse.des";
        TGSResponse tGSResponse = (TGSResponse) fileUtils.readEncryptedObject(clientTGSResponseFilepath);
        System.out.println("***Passo4: Cliente lê o que recebeu do TGS");
        tGSResponse.print();

        sendTicketToServer();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImplementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImplementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImplementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImplementClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImplementClient().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables

    private void initClient() {
        int portAS = 9898;
        int portTGS = 9797;
        int portServer = 9696;

        try {
            // Localiza registro através do IP do servidor e porta
            Registry registryAS = LocateRegistry.getRegistry("localhost", portAS);
            Registry registryTGS = LocateRegistry.getRegistry("localhost", portTGS);
            Registry registryServer = LocateRegistry.getRegistry("localhost", portServer);
            // Localiza através da tag informada
            interfaceAS = (InterfaceAS) registryAS.lookup("HelloServer");
            interfaceTGS = (InterfaceTGS) registryTGS.lookup("HelloServer");
            interfaceServer = (InterfaceServer) registryServer.lookup("HelloServer");
            // Apenas para testes - Servidor manda uma saudação
            System.out.println(interfaceAS.sayHello());
            System.out.println(interfaceTGS.sayHello());
            System.out.println(interfaceServer.sayHello());
        } catch (Exception e) {
            System.out.println("Erro: " + e.getMessage());
        }
    }

    private void sendTicketToServer() throws RemoteException {

        String filepath = "F:\\Kerberos\\Client\\serverTicket.des";
        if (interfaceServer.authenticate(filepath)) {
            JOptionPane.showMessageDialog(rootPane, "Autenticação realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Houve um erro na autentiucação");
        }
    }
}
